version: 0.2

phases:
  pre_build:
    commands:
      - mkdir /opt/sources
      - touch /opt/sources/testing.txt
      - echo Done making directories at /opt/sources
  build:
    commands:
      - echo Building the maven package on `date`
      - mvn clean package
  
  post_build:
    commands:
      - echo Built the spring boot package

artifacts:
  files:
    - target/spring-webapp.jar
  discard-paths: yes